DROP TABLE IF EXISTS TASK;

DROP TABLE IF EXISTS ORIGIN;

CREATE TABLE TASK(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(250) UNIQUE NOT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DUE_DATE_TIME TIMESTAMP
);

CREATE TABLE ORIGIN(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    URI TEXT UNIQUE NOT NULL
);