DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(250) NOT NULL,
    DESCRIPTION TEXT DEFAULT NULL,
    STATUS VARCHAR(20) NOT NULL,
    DUE_DATE_TIME TIMESTAMP
);